# Generated by Django 6.1 on 2026-08-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degreeImage',
            field=models.FileField(blank=True, upload_to='Photos/'),
        ),
    ]
